
version: '3.0'

expectations:
  population_size: 1000

actions:

  codelist_report_02q8kOOWFMYULg0lwvG1Tc:
    run: >
      cohortextractor:latest generate_codelist_report
        --codelist-path=codelist.csv
        --start-date=2019-09-01
        --end-date=2022-06-08
        --output-dir output/02q8kOOWFMYULg0lwvG1Tc
    outputs:
      moderately_sensitive:
        table: output/02q8kOOWFMYULg0lwvG1Tc/counts_per_*.csv
        list_sizes: output/02q8kOOWFMYULg0lwvG1Tc/list_sizes.csv
        patient_count_table: output/02q8kOOWFMYULg0lwvG1Tc/patient_count.csv

  measures_02q8kOOWFMYULg0lwvG1Tc:
    run: python:latest python analysis/generate_measures.py output/02q8kOOWFMYULg0lwvG1Tc
    needs: [codelist_report_02q8kOOWFMYULg0lwvG1Tc]
    outputs:
      moderately_sensitive:
        measure: output/02q8kOOWFMYULg0lwvG1Tc/measure_counts_per_week_per_practice.csv
        events_count_table: output/02q8kOOWFMYULg0lwvG1Tc/event_counts.csv
        practice_count_table: output/02q8kOOWFMYULg0lwvG1Tc/practice_count.csv

  top_5_table_02q8kOOWFMYULg0lwvG1Tc:
    run: python:latest python analysis/top_codes_table.py output/02q8kOOWFMYULg0lwvG1Tc
    needs: [codelist_report_02q8kOOWFMYULg0lwvG1Tc]
    outputs:
      moderately_sensitive:
        table: output/02q8kOOWFMYULg0lwvG1Tc/top_5_code_table.csv

  deciles_charts_02q8kOOWFMYULg0lwvG1Tc:
    run: >
      deciles-charts:v0.0.24
        --input-files output/02q8kOOWFMYULg0lwvG1Tc/measure_counts_per_week_per_practice.csv
        --output-dir output/02q8kOOWFMYULg0lwvG1Tc
    config:
      show_outer_percentiles: false
      tables:
        output: true
      charts:
        output: true
    needs: [measures_02q8kOOWFMYULg0lwvG1Tc]
    outputs:
      moderately_sensitive:
        deciles_charts: output/02q8kOOWFMYULg0lwvG1Tc/deciles_*.*
