
version: '3.0'

expectations:
  population_size: 1000

actions:

  codelist_report_02psXEtD2Ppxpe9rjjoD0T:
    run: >
      cohortextractor:latest generate_codelist_report
        --codelist-path=codelist.csv
        --start-date=2019-09-01
        --end-date=2022-05-11
        --output-dir output/02psXEtD2Ppxpe9rjjoD0T
    outputs:
      moderately_sensitive:
        table: output/02psXEtD2Ppxpe9rjjoD0T/counts_per_*.csv
        list_sizes: output/02psXEtD2Ppxpe9rjjoD0T/list_sizes.csv
        patient_count_table: output/02psXEtD2Ppxpe9rjjoD0T/patient_count.csv

  measures_02psXEtD2Ppxpe9rjjoD0T:
    run: python:latest python analysis/generate_measures.py output/02psXEtD2Ppxpe9rjjoD0T
    needs: [codelist_report_02psXEtD2Ppxpe9rjjoD0T]
    outputs:
      moderately_sensitive:
        measure: output/02psXEtD2Ppxpe9rjjoD0T/measure_counts_per_week_per_practice.csv
        events_count_table: output/02psXEtD2Ppxpe9rjjoD0T/event_counts.csv
        practice_count_table: output/02psXEtD2Ppxpe9rjjoD0T/practice_count.csv

  top_5_table_02psXEtD2Ppxpe9rjjoD0T:
    run: python:latest python analysis/top_codes_table.py output/02psXEtD2Ppxpe9rjjoD0T
    needs: [codelist_report_02psXEtD2Ppxpe9rjjoD0T]
    outputs:
      moderately_sensitive:
        table: output/02psXEtD2Ppxpe9rjjoD0T/top_5_code_table.csv

  deciles_charts_02psXEtD2Ppxpe9rjjoD0T:
    run: >
      deciles-charts:v0.0.24
        --input-files output/02psXEtD2Ppxpe9rjjoD0T/measure_counts_per_week_per_practice.csv
        --output-dir output/02psXEtD2Ppxpe9rjjoD0T
    config:
      show_outer_percentiles: false
      tables:
        output: true
      charts:
        output: true
    needs: [measures_02psXEtD2Ppxpe9rjjoD0T]
    outputs:
      moderately_sensitive:
        deciles_charts: output/02psXEtD2Ppxpe9rjjoD0T/deciles_*.*
