
version: '3.0'

expectations:
  population_size: 1000

actions:

  codelist_report_02qC7dgBZzj931XXykPh1q:
    run: >
      cohortextractor:latest generate_codelist_report
        --codelist-path=codelist.csv
        --start-date=2019-09-01
        --end-date=2022-06-15
        --output-dir output/02qC7dgBZzj931XXykPh1q
    outputs:
      moderately_sensitive:
        table: output/02qC7dgBZzj931XXykPh1q/counts_per_*.csv
        list_sizes: output/02qC7dgBZzj931XXykPh1q/list_sizes.csv
        patient_count_table: output/02qC7dgBZzj931XXykPh1q/patient_count.csv

  measures_02qC7dgBZzj931XXykPh1q:
    run: >
      python:latest python analysis/generate_measures.py
        --start-date=2019-09-01
        --end-date=2022-06-15
        --output-dir output/02qC7dgBZzj931XXykPh1q
        --low-count-threshold 100
        --rounding-base 10
    needs: [codelist_report_02qC7dgBZzj931XXykPh1q]
    outputs:
      moderately_sensitive:
        measure: output/02qC7dgBZzj931XXykPh1q/measure_counts_per_week_per_practice.csv
        events_count_table: output/02qC7dgBZzj931XXykPh1q/event_counts.csv
        practice_count_table: output/02qC7dgBZzj931XXykPh1q/practice_count.csv

  top_5_table_02qC7dgBZzj931XXykPh1q:
    run: >
      python:latest python analysis/top_codes_table.py
        --start-date=2019-09-01
        --end-date=2022-06-15
        --output-dir output/02qC7dgBZzj931XXykPh1q
        --low-count-threshold 100
        --rounding-base 10
    needs: [codelist_report_02qC7dgBZzj931XXykPh1q]
    outputs:
      moderately_sensitive:
        table: output/02qC7dgBZzj931XXykPh1q/top_5_code_table.csv

  deciles_charts_02qC7dgBZzj931XXykPh1q:
    run: >
      deciles-charts:v0.0.24
        --input-files output/02qC7dgBZzj931XXykPh1q/measure_counts_per_week_per_practice.csv
        --output-dir output/02qC7dgBZzj931XXykPh1q
    config:
      show_outer_percentiles: false
      tables:
        output: true
      charts:
        output: true
    needs: [measures_02qC7dgBZzj931XXykPh1q]
    outputs:
      moderately_sensitive:
        deciles_charts: output/02qC7dgBZzj931XXykPh1q/deciles_*.*
