
version: '3.0'

expectations:
  population_size: 1000

actions:

  codelist_report_02qBNa4qKIwzP4nePLICNG:
    run: >
      cohortextractor:latest generate_codelist_report
        --codelist-path=codelist.csv
        --start-date=2019-09-01
        --end-date=2022-06-08
        --output-dir output/02qBNa4qKIwzP4nePLICNG
    outputs:
      moderately_sensitive:
        table: output/02qBNa4qKIwzP4nePLICNG/counts_per_*.csv
        list_sizes: output/02qBNa4qKIwzP4nePLICNG/list_sizes.csv
        patient_count_table: output/02qBNa4qKIwzP4nePLICNG/patient_count.csv

  measures_02qBNa4qKIwzP4nePLICNG:
    run: python:latest python analysis/generate_measures.py output/02qBNa4qKIwzP4nePLICNG
    needs: [codelist_report_02qBNa4qKIwzP4nePLICNG]
    outputs:
      moderately_sensitive:
        measure: output/02qBNa4qKIwzP4nePLICNG/measure_counts_per_week_per_practice.csv
        events_count_table: output/02qBNa4qKIwzP4nePLICNG/event_counts.csv
        practice_count_table: output/02qBNa4qKIwzP4nePLICNG/practice_count.csv

  top_5_table_02qBNa4qKIwzP4nePLICNG:
    run: python:latest python analysis/top_codes_table.py output/02qBNa4qKIwzP4nePLICNG
    needs: [codelist_report_02qBNa4qKIwzP4nePLICNG]
    outputs:
      moderately_sensitive:
        table: output/02qBNa4qKIwzP4nePLICNG/top_5_code_table.csv

  deciles_charts_02qBNa4qKIwzP4nePLICNG:
    run: >
      deciles-charts:v0.0.24
        --input-files output/02qBNa4qKIwzP4nePLICNG/measure_counts_per_week_per_practice.csv
        --output-dir output/02qBNa4qKIwzP4nePLICNG
    config:
      show_outer_percentiles: false
      tables:
        output: true
      charts:
        output: true
    needs: [measures_02qBNa4qKIwzP4nePLICNG]
    outputs:
      moderately_sensitive:
        deciles_charts: output/02qBNa4qKIwzP4nePLICNG/deciles_*.*
